require("chai").should()
const path = require("path")
// const assert = require("assert")
const {extractFromFile} = require(path.join(__dirname, "../extract.js"))
const {writeToWorkbook, createWorkbook} = require(path.join(__dirname, "../excel.js"))

describe("test wirte to excel", function() {
  it("test file: multi nonconformity details && long category title", function() {
    const rtf = extractFromFile(path.join(__dirname, "multi-nonconformity-details.rtf"))
    // console.log(rtf["nonconformity details"])
    const sheetName = "test"
    let workbook = createWorkbook(sheetName)
    let sheet = workbook.getWorksheet(sheetName)
    writeToWorkbook(workbook, sheetName, rtf)

    let row = sheet.getRow(2)

    row.getCell("parseerror").value.should.equal(false)
    row.getCell("season").value.should.equal("F13")
    // row.getCell("department").value.should.equal("35 - Packs")
    row.getCell("reistylenumber").value.should.equal("854042")
    // row.getCell("auditlevel").value.should.equal("Normal")
    row.getCell("auditor").value.should.equal("Asia PQA6")
    row.getCell("productname").value.should.equal("Traverse 30")
    row.getCell("auditqualitylevel").value.should.equal("2.5")
    row.getCell("auditlotsize").value.should.equal("160")
    row.getCell("productionstatus").value.should.equal("Supplier Pre-ship")
    row.getCell("factory").value.should.equal("KANAAN SAIGON CO. LTD")
    row.getCell("vendor").value.should.equal("KAANAN CO., LTD.")
    row.getCell("gaproductnumber").value.should.equal("15978")
    row.getCell("auditsamplequantity").value.should.equal("13")
    row.getCell("ponumber").value.should.equal("4500947614,627")
    row.getCell("auditrejectquantity").value.should.equal("2")
    row.getCell("disposition").value.should.equal("Accept as is")
    row.getCell("reispecinaccuracymajor").value.should.equal(0)
    row.getCell("reispecinaccuracyminor").value.should.equal(0)
    row.getCell("reispecinaccuracyrsi").value.should.equal(0)
    row.getCell("reispecinaccuracycritical").value.should.equal(0)
    row.getCell("trim/findingsmajor").value.should.equal(1)
    row.getCell("trim/findingsminor").value.should.equal(0)
    row.getCell("trim/findingsrsi").value.should.equal(0)
    row.getCell("trim/findingscritical").value.should.equal(0)
  })

  it("test file: multi disposition details && long category title", function() {
    const rtf = extractFromFile(path.join(__dirname, "multi-disposition-details.rtf"))
    const sheetName = "test"
    let workbook = createWorkbook(sheetName)
    let sheet = workbook.getWorksheet(sheetName)
    writeToWorkbook(workbook, sheetName, rtf)
    const row = sheet.lastRow

    row.getCell("parseerror").value.should.equal(false)
    row.getCell("season").value.should.equal("S13")
    // row.getCell("department").value.should.equal("35 - Packs")
    row.getCell("reistylenumber").value.should.equal("844567")
    // row.getCell("auditlevel").value.should.equal("Normal")
    row.getCell("auditor").value.should.equal("Asia PQA2")
    row.getCell("productname").value.should.equal("M Pulaski Short")
    row.getCell("auditqualitylevel").value.should.equal("4.0")
    row.getCell("auditlotsize").value.should.equal("579")
    row.getCell("productionstatus").value.should.equal("Supplier Pre-ship")
    row.getCell("factory").value.should.equal("NANTONG XINLAI SILK GARMENTS CO., LTD.")
    row.getCell("vendor").value.should.equal("TREASURE WILL, HK")
    row.getCell("gaproductnumber").value.should.equal("14216")
    row.getCell("auditsamplequantity").value.should.equal("20")
    row.getCell("ponumber").value.should.equal("4500771596")
    row.getCell("auditrejectquantity").value.should.equal("3")
    row.getCell("disposition").value.should.equal("Vendor 100% Sort/Repair then Ship;Future Factory Audit Required;DC Receipt Audit Required")
    row.getCell("workmanshipmajor").value.should.equal(3)
    row.getCell("workmanshipminor").value.should.equal(0)
    row.getCell("workmanshiprsi").value.should.equal(0)
    row.getCell("workmanshipcritical").value.should.equal(0)
  })

})
